# Generated by Django 5.1.1 on 2024-10-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('is_premium', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('minutes_spent_today', models.IntegerField()),
                ('minutes_spent_this_week', models.IntegerField()),
                ('minutes_spent_this_month', models.IntegerField()),
                ('minutes_spent_in_total', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.user')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
