FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py makemigrations clock && python manage.py migrate && python manage.py migrate clock && daphne -b 0.0.0.0 -p 8000 study_clock.asgi:application"]