services:
    web:
        image: python:3.12
        container_name: django_web
        volumes:
            - .:/app
            - sqlite_data:/app/db
        working_dir: /app
        command: sh -c "pip install -r requirements.txt && daphne -b 0.0.0.0 -p 8000 study_clock.asgi:application"
        ports:
            - "8000:8000"

volumes:
    sqlite_data:
        driver: local